// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Profile.Core;

#nullable disable

namespace Profile.Core.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20211207132923_AddCityTranslations")]
    partial class AddCityTranslations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Profile.Core.Extra.ActiveCity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("ActiveCities", (string)null);
                });

            modelBuilder.Entity("Profile.Core.Extra.ActiveCountry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ActiveCountries", (string)null);
                });

            modelBuilder.Entity("Profile.Core.Extra.User.UserExtraCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("UserExtraCities", (string)null);
                });

            modelBuilder.Entity("Profile.Core.Languages.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AA",
                            Name = "Akhan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AA",
                            Name = "Amharic"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AA",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AA",
                            Name = "Assamese"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AA",
                            Name = "Awadhi"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AA",
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AA",
                            Name = "Balochi"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AA",
                            Name = "Belarusian"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AA",
                            Name = "Bengali"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AA",
                            Name = "Bhojpuri"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AA",
                            Name = "Burmese"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AA",
                            Name = "Cebuano"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AA",
                            Name = "Chewa"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AA",
                            Name = "Chhattisgarhi"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AA",
                            Name = "Chittagonian"
                        },
                        new
                        {
                            Id = 16,
                            Code = "AA",
                            Name = "Czech"
                        },
                        new
                        {
                            Id = 17,
                            Code = "AA",
                            Name = "Deccan"
                        },
                        new
                        {
                            Id = 18,
                            Code = "AA",
                            Name = "Dhundhari"
                        },
                        new
                        {
                            Id = 19,
                            Code = "AA",
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = 20,
                            Code = "AA",
                            Name = "Eastern"
                        },
                        new
                        {
                            Id = 21,
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = 22,
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = 23,
                            Code = "AA",
                            Name = "Fula"
                        },
                        new
                        {
                            Id = 24,
                            Code = "AA",
                            Name = "Gan Chinese"
                        },
                        new
                        {
                            Id = 25,
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Id = 26,
                            Code = "AA",
                            Name = "Greek"
                        },
                        new
                        {
                            Id = 27,
                            Code = "AA",
                            Name = "Gujarati"
                        },
                        new
                        {
                            Id = 28,
                            Code = "AA",
                            Name = "Haitian"
                        },
                        new
                        {
                            Id = 29,
                            Code = "AA",
                            Name = "Hakka"
                        },
                        new
                        {
                            Id = 30,
                            Code = "AA",
                            Name = "Haryanvi"
                        },
                        new
                        {
                            Id = 31,
                            Code = "AA",
                            Name = "Hausa"
                        },
                        new
                        {
                            Id = 32,
                            Code = "AA",
                            Name = "Hiligaynon"
                        },
                        new
                        {
                            Id = 33,
                            Code = "AA",
                            Name = "Hindi"
                        },
                        new
                        {
                            Id = 34,
                            Code = "AA",
                            Name = "Hmong"
                        },
                        new
                        {
                            Id = 35,
                            Code = "AA",
                            Name = "Hungarian"
                        },
                        new
                        {
                            Id = 36,
                            Code = "AA",
                            Name = "Igbo"
                        },
                        new
                        {
                            Id = 37,
                            Code = "AA",
                            Name = "Ilocano"
                        },
                        new
                        {
                            Id = 38,
                            Code = "AA",
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 39,
                            Code = "AA",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 40,
                            Code = "AA",
                            Name = "Javanes"
                        },
                        new
                        {
                            Id = 41,
                            Code = "AA",
                            Name = "Jin"
                        },
                        new
                        {
                            Id = 42,
                            Code = "AA",
                            Name = "Kannada"
                        },
                        new
                        {
                            Id = 43,
                            Code = "AA",
                            Name = "Kazakh"
                        },
                        new
                        {
                            Id = 44,
                            Code = "AA",
                            Name = "Khme"
                        },
                        new
                        {
                            Id = 45,
                            Code = "AA",
                            Name = "Kinyarwanda"
                        },
                        new
                        {
                            Id = 46,
                            Code = "AA",
                            Name = "Kirundi"
                        },
                        new
                        {
                            Id = 47,
                            Code = "AA",
                            Name = "Konkani"
                        },
                        new
                        {
                            Id = 48,
                            Code = "AA",
                            Name = "Korean"
                        },
                        new
                        {
                            Id = 49,
                            Code = "AA",
                            Name = "Kurdish"
                        },
                        new
                        {
                            Id = 50,
                            Code = "AA",
                            Name = "Madures"
                        },
                        new
                        {
                            Id = 51,
                            Code = "AA",
                            Name = "Magahi"
                        },
                        new
                        {
                            Id = 52,
                            Code = "AA",
                            Name = "Maithili"
                        },
                        new
                        {
                            Id = 53,
                            Code = "AA",
                            Name = "Malagas"
                        },
                        new
                        {
                            Id = 54,
                            Code = "AA",
                            Name = "Malay"
                        },
                        new
                        {
                            Id = 55,
                            Code = "AA",
                            Name = "Malayalam"
                        },
                        new
                        {
                            Id = 56,
                            Code = "AA",
                            Name = "Mandarin"
                        },
                        new
                        {
                            Id = 57,
                            Code = "AA",
                            Name = "Marathi"
                        },
                        new
                        {
                            Id = 58,
                            Code = "AA",
                            Name = "Marwari"
                        },
                        new
                        {
                            Id = 59,
                            Code = "AA",
                            Name = "Mossi"
                        },
                        new
                        {
                            Id = 60,
                            Code = "AA",
                            Name = "Nepali"
                        },
                        new
                        {
                            Id = 61,
                            Code = "AA",
                            Name = "Northern Min"
                        },
                        new
                        {
                            Id = 62,
                            Code = "AA",
                            Name = "Odia"
                        },
                        new
                        {
                            Id = 63,
                            Code = "AA",
                            Name = "Orom"
                        },
                        new
                        {
                            Id = 64,
                            Code = "AA",
                            Name = "Pashto"
                        },
                        new
                        {
                            Id = 65,
                            Code = "AA",
                            Name = "Persian"
                        },
                        new
                        {
                            Id = 66,
                            Code = "AA",
                            Name = "Polish"
                        },
                        new
                        {
                            Id = 67,
                            Code = "AA",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = 68,
                            Code = "AA",
                            Name = "Punjabi"
                        },
                        new
                        {
                            Id = 69,
                            Code = "AA",
                            Name = "Quechua"
                        },
                        new
                        {
                            Id = 70,
                            Code = "AA",
                            Name = "Romanian"
                        },
                        new
                        {
                            Id = 71,
                            Code = "AA",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 72,
                            Code = "AA",
                            Name = "Saraiki"
                        },
                        new
                        {
                            Id = 73,
                            Code = "AA",
                            Name = "Serbo - Croatian"
                        },
                        new
                        {
                            Id = 74,
                            Code = "AA",
                            Name = "Shona"
                        },
                        new
                        {
                            Id = 75,
                            Code = "AA",
                            Name = "Sindhi"
                        },
                        new
                        {
                            Id = 76,
                            Code = "AA",
                            Name = "Sinhalese"
                        },
                        new
                        {
                            Id = 77,
                            Code = "AA",
                            Name = "Somali"
                        },
                        new
                        {
                            Id = 78,
                            Code = "AA",
                            Name = "Southern Min"
                        },
                        new
                        {
                            Id = 79,
                            Code = "AA",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 80,
                            Code = "AA",
                            Name = "Sundanese"
                        },
                        new
                        {
                            Id = 81,
                            Code = "AA",
                            Name = "Swedish"
                        },
                        new
                        {
                            Id = 82,
                            Code = "AA",
                            Name = "Sylheti"
                        },
                        new
                        {
                            Id = 83,
                            Code = "AA",
                            Name = "Tagalog / Filipino"
                        },
                        new
                        {
                            Id = 84,
                            Code = "AA",
                            Name = "Tamil"
                        },
                        new
                        {
                            Id = 85,
                            Code = "AA",
                            Name = "Telugu"
                        },
                        new
                        {
                            Id = 86,
                            Code = "AA",
                            Name = "Thai"
                        },
                        new
                        {
                            Id = 87,
                            Code = "AA",
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = 88,
                            Code = "AA",
                            Name = "Turkmen"
                        },
                        new
                        {
                            Id = 89,
                            Code = "AA",
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Id = 90,
                            Code = "AA",
                            Name = "Urdu"
                        },
                        new
                        {
                            Id = 91,
                            Code = "AA",
                            Name = "Uyghur"
                        },
                        new
                        {
                            Id = 92,
                            Code = "AA",
                            Name = "Uzbek"
                        },
                        new
                        {
                            Id = 93,
                            Code = "AA",
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Id = 94,
                            Code = "AA",
                            Name = "Wu"
                        },
                        new
                        {
                            Id = 95,
                            Code = "AA",
                            Name = "Xhosa"
                        },
                        new
                        {
                            Id = 96,
                            Code = "AA",
                            Name = "Xiang"
                        },
                        new
                        {
                            Id = 97,
                            Code = "AA",
                            Name = "Yoruba"
                        },
                        new
                        {
                            Id = 98,
                            Code = "AA",
                            Name = "Yue"
                        },
                        new
                        {
                            Id = 99,
                            Code = "AA",
                            Name = "Zhuang"
                        },
                        new
                        {
                            Id = 100,
                            Code = "AA",
                            Name = "Zulu"
                        });
                });

            modelBuilder.Entity("Profile.Core.Languages.Proficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proficiencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Advanced"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Native"
                        });
                });

            modelBuilder.Entity("Profile.Core.Locations.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlternateNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsciiName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("GeonamesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AsciiName");

                    b.HasIndex("CountryId");

                    b.HasIndex("GeonamesId");

                    b.HasIndex("Name");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Profile.Core.Locations.CityTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Culture")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Culture");

                    b.ToTable("CityTranslations", (string)null);
                });

            modelBuilder.Entity("Profile.Core.Locations.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alpha2")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Alpha3")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Alpha2")
                        .IsUnique()
                        .HasFilter("[Alpha2] IS NOT NULL");

                    b.HasIndex("Alpha3")
                        .IsUnique()
                        .HasFilter("[Alpha3] IS NOT NULL");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Profile.Core.Locations.CountryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Culture")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Culture");

                    b.ToTable("CountryTranslations", (string)null);
                });

            modelBuilder.Entity("Profile.Core.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("InternalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnboarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Profile.Core.Users.UserLanguageProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProficiencyId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProficiencyId");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique();

                    b.ToTable("UserLanguageProficiencies", (string)null);
                });

            modelBuilder.Entity("Profile.Core.Extra.ActiveCity", b =>
                {
                    b.HasOne("Profile.Core.Locations.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Profile.Core.Locations.City", "City")
                        .WithOne()
                        .HasForeignKey("Profile.Core.Extra.ActiveCity", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Profile.Core.Extra.ActiveCountry", b =>
                {
                    b.HasOne("Profile.Core.Locations.Country", "Country")
                        .WithOne()
                        .HasForeignKey("Profile.Core.Extra.ActiveCountry", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Profile.Core.Extra.User.UserExtraCity", b =>
                {
                    b.HasOne("Profile.Core.Locations.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Profile.Core.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Profile.Core.Locations.City", b =>
                {
                    b.HasOne("Profile.Core.Locations.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Profile.Core.Locations.CityTranslation", b =>
                {
                    b.HasOne("Profile.Core.Locations.City", null)
                        .WithMany("Translations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Core.Locations.CountryTranslation", b =>
                {
                    b.HasOne("Profile.Core.Locations.Country", null)
                        .WithMany("Translations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Core.Users.UserLanguageProficiency", b =>
                {
                    b.HasOne("Profile.Core.Languages.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Profile.Core.Languages.Proficiency", "Proficiency")
                        .WithMany()
                        .HasForeignKey("ProficiencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Profile.Core.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Proficiency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Profile.Core.Locations.City", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Profile.Core.Locations.Country", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
